### ISSUE TITLE
"We was"

### ISSUE THREAD

**Issue by allenmanning** [simplenlg/simplenlg#12]
This test fails for me, can this package generate a "we were" instead of "we was".

```
 private void check(String expected, String pronoun, String verb, Tense tense) {
        SPhraseSpec clause = new NLGFactory(englishLexicon).createClause(pronoun, verb);
        clause.setFeature(Feature.TENSE, tense);
        Assert.assertEquals(expected, new Realiser().realiseSentence(clause));
    }

...
    public void testPast_we_were() {
        check("We were.", "we", "be", Tense.PAST); // fails with "we was"
    }

```

**Comment by Saad-Mahamood** [comment]
Hi Allen,

There doesn't seem to be issue with SimpleNLG regarding this. The reason you are getting "We was." is that you need to set the correct features on the clause to get the right conjugation for the verb "be". You may find [this link](http://www.scientificpsychic.com/grammar/to_be.html) useful as it contains a list of different verb conjugations of the verb be and the features required.  Please see the code below that corrects you test and generates the correct sentence:

    public class VerbBeConjugationTest {
	
	private Realiser realiser = null;
	private NLGFactory factory = null;
	
	@Before
	public void setup() {
		// Default Lexicon:
		Lexicon lexicon = Lexicon.getDefaultLexicon();
		factory = new NLGFactory(lexicon);
		realiser = new Realiser(lexicon);	
	}
	
	
	@Test
	public void secondPluralPastTenseTest_WeWere() {
		SPhraseSpec clause = factory.createClause("we", "be");
		clause.setFeature(Feature.TENSE, Tense.PAST);
		clause.setFeature(Feature.PERSON, Person.SECOND);
		clause.setFeature(Feature.NUMBER, NumberAgreement.PLURAL);
		
		Assert.assertEquals("We were.", realiser.realiseSentence(clause));
		
	}
	

    }

**Comment by allenmanning** [comment]
Thanks.  That was it.  Much appreciated.
