### ISSUE TITLE
Support for parentheticals?

### ISSUE THREAD

**Issue by jeremybmerrill** [simplenlg/simplenlg#13]
I'm using simpleNLG to generate a bunch of sentences -- tweets, basically. I've got it all mostly working, but am having some issues getting simpleNLG to generate the right punctuation. I want to be able to generate sentences like _Person has, in every year since 1990, done something._

What I get by creating a basic sentence (that would look like _Person has done something_) and then adding the prepositional phrase as a "pre-modifier" is _Person has, in every year since 1990 done something_ which is not quite valid English because it lacks a comma between _1990_ and _done_.

(I'd be happy to include code, but I'm using a JRuby wrapper library. I'd be happy to include that, if you want.)

SimpleNLG seems to be over-applying the rule that would apply for a sentence like _Person has *cheerfully, quickly and repeatedly* done something_, where there is no comma separating the (in this case adverbial) pre-modifier and the verb. I *think* it's a correct generalization to say that if the pre-modifier is a prepositional phrase or otherwise includes a full clause, it gets commas. I would call this a "parenthetical" though you may have another word for the construction.

So, here's my question:

- Does simpleNLG aim to be able to generate this sort of phrase? If so, how should I do it?
- If not, can you give me some guidance on how to implement it? (I'm not the world's greatest Java programmer, but I can manage.) I took a stab at trying to check in the OrthographyProcessor if a pre_modifier was also a prepositional phrase, but I couldn't ever find anything with the right features/categories. (Is it right that the SyntaxProcessor strips out those features?) If I can manage it, I'll of course submit it as a pull request, if you'd be amenable to merging it.

**Comment by rdeoliveira** [comment]
Jeremy,

 

Are you still looking for a solution for this?

**Comment by jeremybmerrill** [comment]
Hi Rodrigo,

Yes, I am. My project is mostly for fun, so I am not working on it all that often and have found a workaround (not generating sentences with phrasal pre-modifiers), but yes, if there's a solution, I'd love to hear about it!

Thanks,
Jeremy

**Comment by rdeoliveira** [comment]
Ok. I will attempt to say that there is no solution to this with SimpleNLG in its current state. I can take a look at the code in more detail to check whether I’m wrong, an get back to you. But in the meantime, could you send me the sentence specification you’re using to generate your example? So that I know exactly how you’re trying to realise the sentence you need.

**Comment by jeremybmerrill** [comment]
I sure will. Am at work right now, but when I get chance at home (today or tomorrow), will send it to you.

**Comment by Saad-Mahamood** [comment]
Going to close this issue as it should now be fixed. If there is a reoccurrence or another unintended problem please file another issue ticket.
