### ISSUE TITLE
subversion checkout problem

### ISSUE THREAD

**Issue by cchowell** [simplenlg/simplenlg#14]
the presence of the https://github.com/simplenlg/simplenlg/trunk/docs/javadoc/simplenlg/xmlrealiser/wrapper/class-use/.svn folder causes a subversion checkout to fail (it wants to create an administrative folder of that name). This shouldn't be in the repository.

**Comment by Saad-Mahamood** [comment]
I have removed the rouge .svn folder. Please let me know if there are other SVN issues when checking out from GitHub.

**Comment by cchowell** [comment]
have no more svn issues.
