### ISSUE TITLE
Doubled commas when two appositives are next to each other

### ISSUE THREAD

**Issue by jeremybmerrill** [simplenlg/simplenlg#15]
> In every year when a condition occured, since 1999,, except 2001, the Yankees have lost the World Series.

SimpleNLG erroneously generates two commas after "1999" above. Both "since 1999" and "except 2001" are appositives, each added to the prepositional phrase "In every year when a condition occurred"

Here's the code that generates it, using [a fairly simple Ruby library](https://github.com/efi/simplenlg) that interfaces with Java and SimpleNLG: 

```
require 'simplernlg' if RUBY_PLATFORM == 'java'
NLG = SimplerNLG::NLG

subj = NLG.factory.create_noun_phrase('the', "Yankees")
main_clause = {
  :s => subj,
  :number => 'plural',
  :v => "lost", 
  :perfect => true,
  :tense => :present,
  :o => "the World Series",
}
sentence = NLG.phrase(main_clause)

condition_phrase = NLG.phrase({
                          :s => "a condition",
                          :v => "occur",
                          :tense => :past
                      })
condition_phrase.set_feature(NLG::Feature::COMPLEMENTISER, 'when')
year_np = NLG.factory.create_noun_phrase('every', 'year' )
year_np.add_complement(condition_phrase)
prep_phrase = NLG.factory.create_preposition_phrase('in', year_np)

since_pp = NLG.factory.create_preposition_phrase('since', NLG.factory.create_noun_phrase('1999'))
since_pp.set_feature(NLG::Feature::APPOSITIVE, true) # responsible for commas 1 and either 2 or 3

prep_phrase.add_post_modifier(since_pp)

except_phrase = NLG.factory.create_preposition_phrase('except', NLG.factory.create_noun_phrase('2001') )
except_phrase.set_feature(NLG::Feature::APPOSITIVE, true) # responsible for comma 2 or 3
prep_phrase.add_post_modifier(except_phrase)

sentence.add_front_modifier(prep_phrase) 

NLG.realizer.setCommaSepCuephrase(true) # responsible for comma 4
puts NLG.realizer.realise_sentence(sentence) 

# output, with commas numbered
# In every year when a condition occured, since 1999,, except 2001, the Yankees have lost the World Series.
#                                       1           23            4
```
Obviously this isn't a difficult bug to solve in my client code (I can just replace all doubled commas with a single comma), but probably better for SimpleNLG to handle it on its own.

I'm working on getting the other bug (#13) replicated with code for you...

**Comment by rdeoliveira** [comment]
Jeremy, I guess a good starting point to fix this bug would be OrthographyProcessor.java from line 184 onwards.

**Comment by jeremybmerrill** [comment]
Thanks, Rodrigo! I'll take a look. 

I've made a handful of modifications: 

- to add commas around appositive pre-modifiers: 6abc16a7978ac26c8954390aad97c3628c0a3104
- to comma-separate all cue phrases and front modifiers, if commaSepcuephrase is set: https://github.com/jeremybmerrill/simplenlg/commit/5d1252e13a665a29de4243937147c1ab8d2d7346
- and to make the COMPLEMENTISER feature `final`, which I think is necessary to allow it to be set (at least in JRuby): 3eed77f5bf6ce0e2655d80ce3ba453696ad5bb8a

all of the tests pass with this modifications and they enable some sentence structures for me. Would you be interested in pull requests?

**Comment by Saad-Mahamood** [comment]
Jeremy, thanks for contributing your fixes. I have looked at the code changes and they look fine to me. Before I merge, would it be possible to write two JUnit tests as well for the first two code changes in the OrthographyFormatTests class?

**Comment by jeremybmerrill** [comment]
Sure, I'll give that a shot shortly.
