### ISSUE TITLE
push releases to maven central

### ISSUE THREAD

**Issue by jillesvangurp** [simplenlg/simplenlg#21]
I'm currently considering to use simplenlg. It would be helpful for me and probably lots of other interested users if simplenlg releases were available from maven central. This is quite easy to set up via sonatype's hosted maven repository: http://central.sonatype.org/pages/ossrh-guide.html Would you consider doing this?

**Comment by Saad-Mahamood** [comment]
I agree. I applied to the OSSRH for SimpleNLG's inclusion and have updated the pom.xml with deploy details to their Nexus sever. Currently we only have a snapshot version of SimpleNLG currently: https://oss.sonatype.org/content/groups/staging/uk/ac/abdn/SimpleNLG/

**Comment by jillesvangurp** [comment]
Thanks for this!

**Comment by maxhawkins** [comment]
Was this snapshot ever deployed? I don't see it in the central repository.

**Comment by Saad-Mahamood** [comment]
Hi Max,

No it hasn't been deployed to central yet. I will try and organise a new release of SNLG this weekend and see if I can get it deployed onto central as well. 

Thanks,

Saad.

**Comment by Saad-Mahamood** [comment]
I've pushed a release version of SimpleNLG-4.4.8 onto central. Since this is the first release I will have to wait for OSSRH to activate the sync process. You can track the progress of this on this JIRA ticket: https://issues.sonatype.org/browse/OSSRH-16767

**Comment by maxhawkins** [comment]
Thanks. This is great!

**Comment by jillesvangurp** [comment]
Thanks again; painful process with sonatype but once you have the right permissions it gets kind of easy.

**Comment by Saad-Mahamood** [comment]
Central sync has been activated. You can now find SimpleNLG on search.maven.org. Details for the 4.4.8 release are here: http://search.maven.org/#artifactdetails%7Cuk.ac.abdn%7CSimpleNLG%7C4.4.8%7Cjar

Closing this issue.
