### ISSUE TITLE
Dependency Tree to SimpleNLG friendly format

### ISSUE THREAD

**Issue by scottyli** [simplenlg/simplenlg#22]
How could you adapt dependency trees do work with SimpleNLG?

**Comment by Saad-Mahamood** [comment]
Hi Scott,

Are you still looking for an answer to this question? I noticed that you've deleted it, but I haven't had a chance over the past week to reply to you. 

Saad.

**Comment by scottyli** [comment]
Yeah I am :) Any thoughts?

**Comment by Saad-Mahamood** [comment]
It's not something I'm particularly familiar with, but definitely can see the appeal of being able to take a given sentence, transform it into a dependency tree representation and then build an abstract sentence specification for SNLG to realise. There does seem to have been some past work on this in NLG research community:

1. http://citeseerx.ist.psu.edu/viewdoc/download;jsessionid=3A747AFD715064383F3ACA9BDDC42457?doi=10.1.1.412.2762&rep=rep1&type=pdf

2. http://lct-master.org/getfile.php?id=29&n=1&dt=TH&ft=pdf&type=TH

Off the top of my head one issue you will face is that SNLG requires particular linguistic features to be specified to get the correct inflected form. For example specifying present participle for the 'ing' form of a verb or setting the Interrogative feature to generate an Interrogative sentence. The other issue I can think is trying to deal with lexical or syntactically ambiguity, which would need to be dealt with. There are possibly other challenges, but these two ones I could think of straightaway. You might be able to get a better response by mailing the SNLG discussion list: https://groups.google.com/forum/#!forum/simplenlg

Thanks,

Saad Mahamood.

**Comment by scottyli** [comment]
Thanks for the links Saad.

Do you think using PennTreebank style POS tags would resolve most form inflections?

Also, could you give an example of "lexical or syntactical ambiguity" in the DepTree -> SNLG context?

**Comment by Saad-Mahamood** [comment]
Scott,

The only reason why I mentioned lexical ambiguity was because it was something mentioned in the second paper several times when I briefly glanced at it. It may or may not apply to the problem you are looking to solve. 

The PennTreebank POS tags should be good enough for resolving inflected word forms and allow you to work out features you would need to apply in SNLG.

**Comment by Saad-Mahamood** [comment]
Going to close this issue as using a dependency tree as input for SNLG is beyond the scope of this project.
