### ISSUE TITLE
Adding punctuation

### ISSUE THREAD

**Issue by scottyli** [simplenlg/simplenlg#24]
What's the best way to add punctuation for multiple clauses? e.g. "John is a man, but Jane is a woman."

I am currently using ```.setFrontModifier(",")``` or ```.setPostModifier(",")```

Is it better to use the Orthography Processor? If so, how?

**Comment by Saad-Mahamood** [comment]
Scott,

It's better to use the Orthography processor for adding punctuation instead of Front or Post modifiers as these will treat the given String token as a word and you will have to post-process the output to remove the added whitespace. Using the Appositve feature would be more applicable here.

**Comment by scottyli** [comment]
Thanks Saad, what if I wanted to include more punctuation such as ```!```, ```?```, ```()```

It doesn't seem like the ```OrthographyProcessor``` handles these.

Should I just use ```.addFrontModifier()``` and post process myself?

**Comment by Saad-Mahamood** [comment]
You can use the Interrogative feature for question based sentences, but yes the Orthography is currently a weak area of SNLG that needs improvement. So you will have to use the work around that you suggested.
