### ISSUE TITLE
How is the lexicon generated?

### ISSUE THREAD

**Issue by sergiofigueras** [simplenlg/simplenlg#33]
Hey :),

I'm thinking about the accuracy of simplenlg and just one question: how is the lexicon generated? Is it parsed from a single dictionary? There's any technique to measure the performance of it?

**Comment by Saad-Mahamood** [comment]
SimpleNLG has two lexicons:

1. The default XML lexicon which contains around 3,000 base forms. 
2. NIH Lexicon, which SimpleNLG must be configured to use, contains half million base forms. 

The default XML lexicon is a subset of the NIH lexicon and is generated by the following Java class:

https://github.com/simplenlg/simplenlg/blob/master/src/main/java/simplenlg/lexicon/util/NIHLexiconXMLDumpUtil.java

You will get better accuracy with the NIH Lexicon than compared to the XML lexicon, which will use default morphology rules for word inflection. This can result in incorrect word inflections if the word is irregular.

**Comment by Saad-Mahamood** [comment]
Closing issue.
