### ISSUE TITLE
Bug: malformed Perfect tenses

### ISSUE THREAD

**Issue by tezer** [simplenlg/simplenlg#36]
Hi, this code returns "Does John has loved dog?" instead of "Has John loved dog?"

```
    PhraseElement subj = phraseFactory.createNounPhrase("John");
    PhraseElement verb = phraseFactory.createVerbPhrase("love");
    PhraseElement obj = phraseFactory.createNounPhrase("dog");
    SPhraseSpec s = phraseFactory.createClause(subj, verb, obj);
    s.setFeature(Feature.PERFECT, true);
    s.setFeature(Feature.INTERROGATIVE_TYPE, "YES_NO");
    s.setFeature(Feature.TENSE, Tense.PRESENT);
    NLGFactory docFactory = new NLGFactory(lexicon);
    DocumentElement sent = docFactory.createSentence(s);
    return (realiser.realise(sent).getRealisation());
```

Other types of questions work fine.

The Past Perfect has the same bug: "Did John had loved dog?" instead of "Had John loved dog?"

**Comment by philgooch** [comment]
It works for me if you use the PhraseSpec syntax:

```
    NLGFactory nlgFactory = new NLGFactory(lexicon);
    Realiser realiser = new Realiser(lexicon);
    NPPhraseSpec subject;
    NPPhraseSpec object;
    VPPhraseSpec verb;

    SPhraseSpec p = nlgFactory.createClause();

    subject = nlg.nlgFactory.createNounPhrase("John");
    object = nlg.nlgFactory.createNounPhrase("dog");
    object.setDeterminer("the");
    verb = nlg.nlgFactory.createVerbPhrase("love");

    p.setSubject(subject);
    p.setVerb(verb);
    p.setObject(object);

    p.setFeature(Feature.TENSE, Tense.PAST);
    p.setFeature(Feature.PERFECT, true);
    p.setFeature(Feature.INTERROGATIVE_TYPE, InterrogativeType.YES_NO);

    output = nlg.realiser.realiseSentence(p);

    nlg.logger.info(output);
```

**Comment by pekoli** [comment]
I get the same error as @tezer with the code from @philgooch as shown above, adding
`Lexicon lexicon = Lexicon.getDefaultLexicon();`
The result is "Did John had loved the dog?"
I'm on the current master branch (`SimpleNLG-4.4.9-SNAPSHOT.jar`).
I think the error is in method `realiseYesNo()` of `ClauseHelper.java`. The` if` condition does not check for perfect tense before calling `addDoAuxiliary()`. If I add
`&& !phrase.getFeatureAsBoolean(Feature.PERFECT).booleanValue()`
to the [if condition](https://github.com/simplenlg/simplenlg/blob/master/src/main/java/simplenlg/syntax/english/ClauseHelper.java#L702) then the output is "Had John loved the dog?" and all tests still succeed.
