### ISSUE TITLE
Future tense of 'be' provides multiple 'will'

### ISSUE THREAD

**Issue by mcdee** [simplenlg/simplenlg#44]
Given a simple code fragment:

      final Lexicon lexicon = Lexicon.getDefaultLexicon();
      final NLGFactory nlgFactory = new NLGFactory(lexicon);
      final Realiser realiser = new Realiser(lexicon);

      final SPhraseSpec clause = nlgFactory.createClause();
      clause.setFeature(Feature.TENSE, Tense.FUTURE);

      final NPPhraseSpec subject = nlgFactory.createNounPhrase("train");
      subject.setDeterminer("the");
      clause.setSubject(subject);

      final VPPhraseSpec verb = nlgFactory.createVerbPhrase("be");
      clause.setVerb(verb);

      final AdjPhraseSpec object = nlgFactory.createAdjectivePhrase("late");
      clause.setObject(object);

      final String result = realiser.realiseSentence(clause);
      Assert.assertEquals(result, "The train will be late.");

Result produced is "The train will will be late."

Changing the clause tense to PRESENT gives the expected "The train is late." and to PAST gives the expected "The train was late."

**Comment by rdeoliveira** [comment]
**'Hot fix':** 
change `clause.setVerb(verb);` for `clause.setVerbPhrase(verb);` **or** 
`clause.setVerb(verb);` for `clause.setVerb("be");`

**Discussion**
I do not blame your code though; I personally think `setVerb()` and `setVerbPhrase()` are confusing and I would have probably made the same 'mistake'. I'll try to play around with those functions -- e.g. get rid of one -- and see where/if things break. What happens is that `setVerb()` creates a nested verb phrase in the clause if you pass on a VerbPhrase, which is what you do. The first "will" is the modal of the outer verb phrase and the second "will" is the modal of the nested one. Again, I don't think you (the user) should worry about passing phrases or strings, but the system should work out the rest. For now, I'd suggest using the 'hot fix' above.

**Comment by Saad-Mahamood** [comment]
Closing this issue.
