### ISSUE TITLE
Correct way to form "is expected"?

### ISSUE THREAD

**Issue by mcdee** [simplenlg/simplenlg#45]
I'm attempting to create a simple sentence "The train is expected to arrive at 6:15pm".  So far I have:

    final Lexicon lexicon = Lexicon.getDefaultLexicon();
    final NLGFactory nlgFactory = new NLGFactory(lexicon);
    final Realiser realiser = new Realiser(lexicon);

    final SPhraseSpec clause = nlgFactory.createClause();
    final NPPhraseSpec subject = nlgFactory.createNounPhrase("train");
    subject.setDeterminer("the");
    clause.setSubject(subject);

    final VPPhraseSpec verb = nlgFactory.createVerbPhrase("expect");
    clause.setFeature(Feature.TENSE, Tense.PAST);
    verb.addPreModifier("is");

    final VPPhraseSpec cVerb = nlgFactory.createVerbPhrase("arrive");
    cVerb.setFeature(Feature.FORM, Form.INFINITIVE);
    verb.setComplement(cVerb);
    clause.setVerb(verb);

    final PPPhraseSpec preposition = nlgFactory.createPrepositionPhrase();
    preposition.setPreposition("at");
    preposition.setObject("6:15pm");
    clause.setComplement(preposition);

    final String result = realiser.realiseSentence(clause);
    Assert.assertEquals(result, "The train is expected to arrive at 6:15pm.");

However the creation of the "is expected to" piece doesn't feel at all right, not least because changing the tense occurs for the entire clause.  Is there a better supported way to do this?

**Comment by rdeoliveira** [comment]
Jim, "it doesn't feel right", because the clause you want is in the **passive voice**, which SimpleNLG supports, but you're trying to passivise the clause manually, and treating "is" as canned text, instead of a form of the verb "be". 

To use SimpleNLG's passivisation algorithm, you need to declare the resulting subject as the input object, because SimpleNLG assumes a "before passivisation" input; see **solution A**. 

But if you'd rather build the passivisation by hand, I would declare the auxiliary "be" as main verb (so that it can agree with the after-passivisation subject) and "expect" in the past participle form; see **solution B**. It's important to differentiate `Tense` from `Form`: tense modifies the whole clause, whereas form modifies only the word (the verb in this case). Main verbs in the passive voice ("expect" in your case) are in the past participle form (expected), regardless of the clause being in the present tense (is expected) or past tense (was expected).

**Solution A**

        final Lexicon lexicon = Lexicon.getDefaultLexicon();
	final NLGFactory nlgFactory = new NLGFactory(lexicon);
	final Realiser realiser = new Realiser(lexicon);
	final SPhraseSpec clause = nlgFactory.createClause();
	final NPPhraseSpec subject = nlgFactory.createNounPhrase("train");
	subject.setDeterminer("the");
	// Making the subject be the object:
	// clause.setSubject(subject);
	clause.setObject(subject);

	// Making "expect" the main verb and the whole clause passive:
	// final VPPhraseSpec verb = nlgFactory.createVerbPhrase("expect");
	// clause.setFeature(Feature.TENSE, Tense.PAST);
	// verb.addPreModifier("is");
	final VPPhraseSpec verb = nlgFactory.createVerbPhrase("expect");
	clause.setFeature(Feature.PASSIVE, true);
	clause.setVerb(verb);

	final VPPhraseSpec cVerb = nlgFactory.createVerbPhrase("arrive");
	cVerb.setFeature(Feature.FORM, Form.INFINITIVE);
	// Making "arrive" a complement of "expect", not the whole clause:
	verb.setComplement(cVerb);
	// clause.setVerb(verb);

	final PPPhraseSpec preposition = nlgFactory.createPrepositionPhrase();
	preposition.setPreposition("at");
	preposition.setObject("6:15pm");
	// Making the PP a complement of "arrive", not the whole clause:
	// clause.setComplement(preposition);
	cVerb.setComplement(preposition);

	final String result = realiser.realiseSentence(clause);
	// Fixing the order of actual and expected in this JUnit method:
	// Assert.assertEquals(result, "The train is expected to arrive at
	// 6:15pm.");
	assertEquals("The train is expected to arrive at 6:15pm.", result);

**Solution B**

        final Lexicon lexicon = Lexicon.getDefaultLexicon();
	final NLGFactory nlgFactory = new NLGFactory(lexicon);
	final Realiser realiser = new Realiser(lexicon);

	final SPhraseSpec clause = nlgFactory.createClause();
	final NPPhraseSpec subject = nlgFactory.createNounPhrase("train");
	subject.setDeterminer("the");
	clause.setSubject(subject);

	// Making "be" the main verb:
	// verb.addPreModifier("is");
	final VPPhraseSpec verb1 = nlgFactory.createVerbPhrase("be");
	clause.setVerb(verb1);

	// Making "expect" a complement of "be" with its correct form (not
	// tense):
	// final VPPhraseSpec verb = nlgFactory.createVerbPhrase("expect");
	// clause.setFeature(Feature.TENSE, Tense.PAST);
	final VPPhraseSpec verb2 = nlgFactory.createVerbPhrase("expect");
	verb2.setFeature(Feature.FORM, Form.PAST_PARTICIPLE);
	verb1.setComplement(verb2);

	final VPPhraseSpec cVerb = nlgFactory.createVerbPhrase("arrive");
	cVerb.setFeature(Feature.FORM, Form.INFINITIVE);
	// Making "arrive" a complement of "expect", not the whole clause:
	verb2.setComplement(cVerb);
	// clause.setVerb(verb);

	final PPPhraseSpec preposition = nlgFactory.createPrepositionPhrase();
	preposition.setPreposition("at");
	preposition.setObject("6:15pm");
	// Making the PP a complement of "arrive", not the whole clause:
	// clause.setComplement(preposition);
	cVerb.setComplement(preposition);

	final String result = realiser.realiseSentence(clause);
	// Fixing the order of actual and expected in this JUnit method:
	// Assert.assertEquals(result, "The train is expected to arrive at
	// 6:15pm.");
	assertEquals("The train is expected to arrive at 6:15pm.", result);

**Comment by mcdee** [comment]
Thank you for the explanation.
