### ISSUE TITLE
Verbs as subjects and objects

### ISSUE THREAD

**Issue by natewatson999** [simplenlg/simplenlg#48]
There is a problem with using verbs as subjects. When a verb is used as a subject, the verb is set to progressive, and the containing sentence is realized, it's preceded with the word "is". It should just be converted to a progressive verb.
`
final SPhraseSpec p = nlgFactory.createClause();
final VPPhraseSpec sub = nlgFactory.createVerbPhrase("spend");
sub.setFeature(Feature.PROGRESSIVE, true);
final VPPhraseSpec verb=nlgFactory.createVerbPhrase("endanger");
final NPPhraseSpec object=nlgFactory.createNounPhrase("safety");
object.setPreModifier(nlgFactory.createAdjectivePhrase("financial"));
p.setSubject(sub);
p.setVerb(verb); 
p.setObject(object);
System.out.println(realiser.realise(p));
`

Yields "is spending endangers financial safety". It should yield "Spending endangers financial safety.".

**Comment by shrikant14** [comment]
You have to set verb form as gerund instead of converting it to progressive form.
replace this line sub.setFeature(Feature.PROGRESSIVE, true);
with sub.setFeature(Feature.FORM,Form.GERUND);

**Comment by natewatson999** [comment]
Roger. Thank's for clarifying that. I'm closing this issue.
