### ISSUE TITLE
support for rich text?

### ISSUE THREAD

**Issue by AlJohri** [simplenlg/simplenlg#49]
Does SimpleNLG have some basic support for rich text via HTML such as adding links via `a` tags?

**Comment by Saad-Mahamood** [comment]
Hi,

At the moment SimpleNLG has support for basic HTML formatting using the implementation found in the [HTMLFormatter](https://github.com/simplenlg/simplenlg/blob/master/src/main/java/simplenlg/format/english/HTMLFormatter.java) class. It doesn’t really have support for HTML hyperlinks and formatting such as Bold, Italics, and Underlined markup. It would be possible to extend the current implementation to include support for these additional types of HTML markup, but it’s something I won’t able to add immediately. Obviously feel free to extend the code yourself and I’d be more than happy to merge your contribution!

Thanks,

Saad.
