### ISSUE TITLE
Can I use the Simple NLG Library (JAR) in Proprietary software (Commercial use)

### ISSUE THREAD

**Issue by lokeshkumarn** [simplenlg/simplenlg#51]
Hi team
Can I use the Simple NLG Library (JAR) in Proprietary software (Commercial use)
I am not going to modify Simple NLG Code and just going to use the Library as it is

Since it is licensed under MPL 1.1 , I am facing difficulties in understanding it

**Comment by Saad-Mahamood** [comment]
It is permissible to use SimpleNLG as a dependency in a proprietary software for commercial use (Section 3.7). If you do distribute SimpleNLG as part of a commercial software my understand is that as part of Section 3.5 you must include a notice that states that SimpleNLG is covered under the terms of MPL 1.1 license. 

The MPL licence will also come into play if you make *modifications* to the SimpleNLG code base. These changes must be open sourced or committed back to the SimpleNLG project for a period of up to 3 years.

Many Thanks,

Saad Mahamood.
