### ISSUE TITLE
SimpleNLG tests fail under Java 9

### ISSUE THREAD

**Issue by Saad-Mahamood** [simplenlg/simplenlg#54]
Java 9 removes some JAXB libraries that were used by the server component of SimpleNLG and thus causes ClassNotFound exceptions. This Stackoverflow post (https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j#43574427) describes the problem and gives some solutions, but the challenge here is to SimpleNLG working across Java 8 and 9:

**Comment by Marthe22** [comment]
Hi, 
Have you found a solution to this problem? I am encountering the same issue. 
Thank you!

**Comment by Saad-Mahamood** [comment]
Fixed now in commit b3fb854c297785418a61d11bbd845b2843635092.
