### ISSUE TITLE
XmlRealiser verb morphology incorrect for perfect passive

### ISSUE THREAD

**Issue by krivard** [simplenlg/simplenlg#58]
Hi, I think I've found a bug in XmlRealiser:

- Test sentence: The child upset the man
- Configuration: +passive, +perfect
- Expected result (returned by non-XML Realiser): The man has been upset by the child
- Actual result (returned by XmlRealiser): The man haves been upset by the child

I've done some digging, and it looks like the problem is with how XmlRealiser creates a Realiser object. Realiser calls initialise() on itself during construction, in such a way that SyntaxProcessor is given access to the lexicon. XmlRealiser then (I suspect needlessly?) calls Realiser.initialise() again, wiping out the lexicon-enabled SyntaxProcessor and substituting a lexicon-less one. This screws up the base-word feature that would let the MorphologyProcessor do the right thing with the verb. Details below.

Here's my sentence, constructed using the API:

```
        VPPhraseSpec vp = nlgFactory.createVerbPhrase("upset");
        vp.addComplement(nlgFactory.createNounPhrase("the","man"));
        SPhraseSpec finished = nlgFactory.createClause(
                nlgFactory.createNounPhrase("the","child"),
                vp
        );
        finished.setFeature(Feature.TENSE,Tense.PRESENT);
        finished.setFeature(Feature.PASSIVE,true);
        finished.setFeature(Feature.PERFECT,true);
```

When I render it like so, I get the desired result:

```
    Lexicon lexicon = Lexicon.getDefaultLexicon();
    NLGFactory nlgFactory = new NLGFactory(lexicon);
    Realiser realiser = new Realiser(lexicon);
    System.out.println(realiser.realiseSentence(finished));
```

When I define the same sentence in XML, and render it using XmlRealiser, I get the unexpected result. Here's the XML I'm using:

```
<?xml version="1.0" encoding="UTF-8"?>
<NLGSpec xmlns="http://simplenlg.googlecode.com/svn/trunk/res/xml" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Request>
      <Document cat="SENTENCE">
        <child xsi:type="SPhraseSpec" PASSIVE="true" TENSE="PRESENT" PERFECT="true">
          <subj xsi:type="NPPhraseSpec">
            <head cat="NOUN">
              <base>child</base>
            </head>
            <spec xsi:type="WordElement" cat="DETERMINER">
              <base>the</base>
            </spec>
          </subj>
          <vp xsi:type="VPPhraseSpec" PASSIVE="true">
            <compl xsi:type="NPPhraseSpec">
              <head cat="NOUN">
                <base>man</base>
              </head>
              <spec xsi:type="WordElement" cat="DETERMINER">
                <base>the</base>
              </spec>
            </compl>
            <head cat="VERB">
              <base>upset</base>
            </head>
          </vp>
        </child>
      </Document>
  </Request>
</NLGSpec>
```

And here's the code I'm realising it with:

```
            RequestType request = XMLRealiser.getRequest(new StringReader(xml_content));
            System.out.println(XMLRealiser.realise(request.getDocument()));
```

**Comment by Saad-Mahamood** [comment]
Hi,

Thanks for taking the time to report this issue. I will take a look and get back to you as soon as possible. 

Thanks,

Saad.

**Comment by Saad-Mahamood** [comment]
It's seems that issue may of been fixed already. I've added the a test case called `xmlPerfectPassiveTest` in the JUnit class `XMLRealiserTest`.
