### ISSUE TITLE
Clause vs Sentence

### ISSUE THREAD

**Issue by atotalnoob** [simplenlg/simplenlg#60]
It isn't explained anywhere the difference between createClause() and createSentence(). 

What is the difference?

**Comment by rdeoliveira** [comment]
For practical purposes, sentence = clause + orthography (capitalisation and punctuation). So:

- createClause("she", "like", "chocolate”) → "she likes chocolate”
- createSentence("she", "like", "chocolate”) → "She likes chocolate.”

Hope this helps.

r

**Comment by atotalnoob** [comment]
Thanks, that explains it.
