### ISSUE TITLE
wiki pages are writable for logged in user

### ISSUE THREAD

**Issue by gear0** [simplenlg/simplenlg#61]
Hi, 
I am reading through the simplenlg wiki (https://github.com/simplenlg/simplenlg/wiki) and noticed that I can edit wiki pages even though I don't have write permissions to the main repo. I don't know if it is the intention that every logged-in user can edit the wiki or not.

**Comment by Saad-Mahamood** [comment]
I think it's the way GitHub has setup Wiki pages. I can't see a way of restricting editing of the Wiki pages.

**Comment by gear0** [comment]
You are welcome. Thanks for enabling it
