### ISSUE TITLE
Trying to implement simpleNLG in python 

### ISSUE THREAD

**Issue by stalwar5** [simplenlg/simplenlg#66]
I was trying to implement simplenlg in python - I used the following code from the internet. However, it gives me an error when I call the methods of the simplenlg library. The error specifically is, " "JavaPackage" object is not callable " 

#using py4j to use the code of simplenlg (java) in python
from py4j.java_gateway import JavaGateway, GatewayClient, java_import,launch_gateway

port_val = launch_gateway()
gateway = JavaGateway(GatewayClient(port=port_val)) # = port_val insures that the ports on both ends are equal (java and python)

#importing the simpleNLG classes 
java_import(gateway.jvm, "simplenlg.features.*")
java_import(gateway.jvm, "simplenlg.realiser.*")
java_import(gateway.jvm, "simplenlg.framework.*")
java_import(gateway.jvm, "simplenlg.lexicon.*")
java_import(gateway.jvm, "simplenlg.phrasespec.*")

#creating aliases to not use the gateway.jvm prefix each time 
NPPhraseSpec = gateway.jvm.NPPhraseSpec
PPPhraseSpec = gateway.jvm.PPPhraseSpec
VPPhraseSpec = gateway.jvm.VPPhraseSpec
SPhraseSpec = gateway.jvm.SPhraseSpec
InterrogativeType = gateway.jvm.InterrogativeType
NLGFactory = gateway.jvm.NLGFactory
Realiser = gateway.jvm.Realiser
TextSpec = gateway.jvm.TextSpec
Tense = gateway.jvm.Tense
Form = gateway.jvm.Form

Phrase = SPhraseSpec()

I don't know much about java and would really appreciate any way to implement this library in python. Thank you!!!

**Comment by Saad-Mahamood** [comment]
Unfortunately, I'm particularly familiar with Py4J, but I have used Jython successfully in the past to run SimpleNLG in a Python language context.

**Comment by stalwar5** [comment]
How did you go about doing that?

**Comment by Saad-Mahamood** [comment]
Using Jython 2.7.1:

`Jython 2.7.1 (default:0df7adb1b397, Jun 30 2017, 19:02:43)
[OpenJDK 64-Bit Server VM (Amazon.com Inc.)] on java1.8.0_212
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path.append("SimpleNLG-4.4.8.jar")
>>> from simplenlg.lexicon import Lexicon
>>> from simplenlg.framework import NLGFactory
>>> from simplenlg.realiser.english import Realiser
>>> lexicon = Lexicon.getDefaultLexicon()
>>> nlgFactory = NLGFactory(lexicon)
>>> realiser = Realiser(lexicon)
>>> phrase = nlgFactory.createClause()
>>> phrase.setSubject("Mary")
>>> phrase.setVerb("chase")
>>> phrase.setObject("the monkey")
>>> output = realiser.realiseSentence(phrase)
>>> print(output)
Mary chases the monkey.`

**Comment by stalwar5** [comment]
Thank you so much! Just to confirm, this has all the functionality of simplenlg?

**Comment by stalwar5** [comment]
Because I get the following errors:
` 
subject` = nlgFactory.createNounPhrase("Han")
object1 = nlgFactory.createNounPhrase("boy")
verb = nlgFactory.createVerbPhrase("race")
subject.addModifier("fast")
object1.addModifier("young")
object1.setDeterminer("the")

s3 = nlgFactory.createClause()
s3.setSubject(subject) 
s3.setObject(object1)
s3.setVerb(verb)

#s3.setFeature(Feature.NEGATED,True)
#gives the following error - "Fast Han does not does not race the young boy."

#s3.setFeature(Feature.TENSE, Tense.PAST)
#gives the following error - "Fast Han races the young boy." 

output1 = realiser.realiseSentence(s3)
print(output1) 
`

**Comment by stalwar5** [comment]
This is the last part needed to configure my project - I'd really appreciate your help :)
