### ISSUE TITLE
Use SimpleNLG under MPL 2.0?

### ISSUE THREAD

**Issue by ramonziai** [simplenlg/simplenlg#71]
SimpleNLG is currently licensed under the terms of the MPL, version 1.1. However, unless I'm mistaken, this version of the license is not automatically compatible with other popular open-source licenses, such as the Apache License 2.0 or the GPL and thus prohibits the combination with libraries under these licenses in a larger work. MPL 2.0 was created to achieve just that compatibility (https://en.wikipedia.org/wiki/Mozilla_Public_License).

Would it be possible to use SimpleNLG under MPL 2.0?

**Comment by Saad-Mahamood** [comment]
Hi @ramonziai,

Yes I will look into re-licensing SimpleNLG to MPL 2.0. In theory this shouldn’t pose a problem to do so but I will need to check first. I’ll keep this issue open until I have answer one way or the other. 


Saad.

**Comment by Saad-Mahamood** [comment]
Yes it shouldn't be a problem re-licensing SimpleNLG to MPL 2.0. The next release 4.49 will be released under the MPL 2.0 license.

**Comment by ramonziai** [comment]
Great, thank you!
