### ISSUE TITLE
is simplenlg project alive?

### ISSUE THREAD

**Issue by traut** [simplenlg/simplenlg#74]
With the latest update on Aug 2018 and no follow up on many open issues, @Saad-Mahamood could you please elaborate on the status of the project?

**Comment by Saad-Mahamood** [comment]
Hi Sergey,

The project is still being maintained and I have recently built an internal system that utilises SimpleNLG and it is being used by other folks in either in industry or academia. I just haven’t much personal time to work on the project recently. I would like to do a new release 4.49 that address some of the open issues for this year. I am always willing to accept contributions to SimpleNLG and will be ready and responsive if such contributions arrive. 

Many Thanks,

Saad Mahamood.

**Comment by oliveratutexas** [comment]
@Saad-Mahamood if you have that work in other branches could you push them please?

**Comment by Saad-Mahamood** [comment]
Just committed my current set of changes. Including updating the license to MPL 2.0 and fixing a minor issue in #54 where test were not passing on JDK versions greater than 9.
