### ISSUE TITLE
expletive ("there is/are ...")

### ISSUE THREAD

**Issue by miwieg** [simplenlg/simplenlg#78]
I was wondering how expletive constructions can be generated with simplenlg.
I am interested in sentences:
"There is one monkey." vs. "There are two monkeys."

Obviously, the following naive encoding:
`		SPhraseSpec p = nlgFactory.createClause();
		p.setSubject("There");
		p.setVerb("be");
		NPPhraseSpec np = nlgFactory.createNounPhrase("two monkeys");
		np.setPlural(true);
		p.setObject(np);
		p.setFeature(Feature.TENSE,Tense.PRESENT);
`
does not work. It results in
*There is two monkeys.

Is there any possibility to get these constructions right in simplenlg?

Thank you very much.

**Comment by rdeoliveira** [comment]
**Short answer**
Lower-case "there" and it should work.

**Long answer**
Tricky one.
SimpleNLG does an exact-match, case-sensitive comparison to detect pronouns. "there" is an expletive pronoun, while "There" is assumed to be a random word.
Note that this is helpful at times:

`SPhraseSpec p = nlgFactory.createClause("Her", "be", "a great AI movie.");`
> Her is a great AI movie.

The movie named "Her" is a great AI movie.

`SPhraseSpec p = nlgFactory.createClause("her", "be", "a great AI movie.");`
> Hers is a great AI movie.

A movie by a female director is a great AI movie.

So a bit tricky to call this a 'bug' and create a pull request to _fix_ this, or leave it as an _undocumented feature_ =) .

**Comment by miwieg** [comment]
I can confirm that it works with lowercase.
As far as I am concerned I consider this issue as solved.
Thank you very much for your help.
