### ISSUE TITLE
Example of either...or, neither...nor sentences

### ISSUE THREAD

**Issue by lekhnath** [simplenlg/simplenlg#87]
How to generate the following sentence in SimpleNLG.

> The first one is not good, neither is the second one.

I wrote following piece of code and gave me the result with additional comma at the end of the sentence.

> The first one is not good, neither is the second one,.

**NOTE: I am using the simplenlg java library with python using py4j**

```python
s = nlgFactory.createClause()

sub = nlgFactory.createNounPhrase('the', 'first one')
s.setSubject(sub)
s.setVerb('be')
s.setObject('good')

s.setFeature(Feature.NEGATED, True)

v2 = nlgFactory.createVerbPhrase('be')
v2.addComplement('the second one')
v2.addPreModifier('neither')
v2.setFeature(Feature.APPOSITIVE, True)

s.addModifier(v2)

print(realiser.realiseSentence(s))

```

Asked for a help in [StackOverflow](https://stackoverflow.com/questions/69424406/how-to-add-comma-in-sentence-generated-with-simplenlg) site also.

**Comment by Saad-Mahamood** [comment]
Closing issue due the amount of time passed and the fact it is a query rather than a specific issue with SimpleNLG.
