### ISSUE TITLE
Example of "will also be ..."

### ISSUE THREAD

**Issue by lekhnath** [simplenlg/simplenlg#89]
How do I generate "I will also be doing my homework" ? I am only able to generate "I will be doing my homework".

```python
_s = nlgFactory.createClause()
_s.setSubject('i')
_s.setVerb('do')
_s.setObject('my homework')

_s.setFeature(Feature.TENSE, Tense.FUTURE)
_s.setFeature(Feature.PROGRESSIVE, True)
```

**Comment by Saad-Mahamood** [comment]
Closing issue due the amount of time passed and the fact it is a query rather than a specific issue with SimpleNLG.
